Include fragments on html files
Skallwar/suckit pull request #207
Opened 2023-01-12 05:22 UTC by AOx0

My use case requires `suckit` to maintain fragments within paths, for example, `href="#sub-title"`.
I re-enabled the fragment part only for the downloaded Html files. The visited hash map only records the Url's path without storing it.

One downside of the implementation is the introduction of an additional argument.

```rust
pub fn to_path(url: &Url, with_fragment: bool) -> String { ... }
```

I'm making this PR in case anybody needs the feature. From my point of view, it is essential. 

Have a nice day.

2023-01-14 11:21 UTC, Skallwar requested changes
Good catch! Thanks for your time and effort :rocket:
I just have a minor nitpick but this will be merged

2023-01-14 12:04 UTC, CohenArthur approved these changes

2023-01-14 16:50 UTC, AOx0 commented on src/url_helper.rs
> +        (None, true) => format!("{}{}/{}", url_domain, parent, filename),
I changed it in the latest commit to this..
```rust 
    match (url.fragment(), with_fragment) {
        (Some(fragment), true) => format!("{}{}/{}#{}", url_domain, parent, filename, fragment),
        (_, _) => format!("{}{}/{}", url_domain, parent, filename),
    }
```
You are right, we only care if there is a fragment and if `with_fragment` is true.

2023-01-15 22:14 UTC, Skallwar approved these changes
Thanks again

2023-01-15 22:14 UTC, merged